#Form
$Label3.Text = "erstellt von MinersWin"

#Registry Tweaks
$CheckBox1.Text = "Zeige die 'Dieser PC' Verknüpfung auf dem Desktop"
$CheckBox2.Text = "Zeige die 'Netzwerk' Verknüpfung auf dem Desktop"
$CheckBox3.Text = "Klassischer Vertikaler Symbolabstand"
$checkBox4.Text = "Fixiere die Taskleiste"
$CheckBox5.Text = "Zeige immer alle Icons in der Taskleiste"
$checkBox6.Text = "Verzögere die Anzeige von Miniaturansichten in der Taskleiste um 10 Sekunden"
$CheckBox7.Text = "Aktiviere die Klassische Systemsteuerungsansicht"
$CheckBox8.Text = "Deaktivieren der Einrastfunktion beim 5 maligen Drücken der SHIFT Taste"
$CheckBox9.Text = "Deaktivieren der Filterfunktion beim 8 Sekunden langen drücken der SHIFT Taste"
$CheckBox10.Text = "Deaktiviere den Ruhemodus"
$CheckBox11.Text = "Unterstreiche Tastenkombinationen und Zugangsschlüssel"
$CheckBox12.Text = "Zeige Dateiendungen im Windows Explorer"
$checkBox13.Text = "Komprimierte NTFS-Dateien ausblenden"
$CheckBox14.Text = "Zeige Versteckte Daten"
$CheckBox15.Text = "Zeige Versteckte Systemdaten"
$CheckBox17.Text = "Ersetze die Utilman.exe mit der Cmd.exe"
$CheckBox18.Text = "Parke nur noch die Minimale Anzahl an Kernen"
$CheckBox19.Text = "Deaktiviere CPU-Core-Parking"
$CheckBox20.Text = "Entferne das Hintergrundbild im Anmeldebildschirm und setzte eine Statische Farbe (BLAU)"
$CheckBox21.Text = "Deaktiviere den Sperrbildschirm"
$CheckBox22.Text = "Entferne den Vorgängerversionen Tab aus den Eigenschaften"
$CheckBox23.Text = "Deaktiviere Jump Lists"
$CheckBox24.Text = "Deaktiviere das Senden von Errormeldungen an Microsoft"
$CheckBox25.Text = "Deaktiviere Cortana (Sprache und Suchhilfe, welche auch Informationen an Microsoft sendet)"
$CheckBox26.Text = "Verstecke die Suchbox aus der Taskleiste (Das Suchen über das Startmenü ist immer noch möglich)"
$CheckBox27.Text = "MRU-Listen (Jump Lists) von XAML-Apps im Startmenü deaktivieren"
$CheckBox29.Text = "Deaktivieren Sie die Registerkarte Datenträgerkontingent, die als Registerkarte in den Eigenschaften eines Laufwerks angezeigt wird"
$CheckBox30.Text = "Verhindere die erstellung einer Werbe-ID"
$CheckBox31.Text = "Entferne 'An Start anheften'"
$CheckBox32.Text = "Deaktiviere Cortana, Bing, Suche und die Suchleiste"
$CheckBox33.Text = "Deaktiviere den Error Dialog"
$CheckBox34.Text = "Deaktiviere Administrative Freigaben"
$CheckBox35.Text = "Füge 'Reboot to Recovery' zum Rechtsklickmenü von 'Dieser PC' hinzu"
$CheckBox36.Text = "Änder das Uhrzeit und Datumsformat des Angemeldeten Nutzers zu 24H, metrisch"
$CheckBox37.Text = "Aktiviere den Developer (Programmierer) Modus"
$Checkbox38.Text = "Entferne die Nutzungs und Datenerfassung von Microsoft"
$CheckBox28.Text = "Setze den Windows Explorer Start zu 'Dieser PC' anstatt 'Zuletzt Verwendet'"
$CheckBox16.Text = "Hinder Windows und Office daran LNK Daten im 'Zuletzt Verwendet' Ordner zu erstellen."
$CheckBox76.Text = "Zeige das User Profil auf dem Desktop"
$CheckBox77.Text = "zeige die Systemsteuerung auf dem Desktop"

#Removing Services
$CheckBox39.Text = "Deaktivieren der Telemetrie und Datenerfassung"
$CheckBox40.Text = "Deaktiviere Diagnose Service"
$checkBox41.Text = "Deaktiviere den Distributed Link Tracking Client (Wenn der computer mit keinem Netzwerk verbunden ist)"
$CheckBox42.Text = "Deaktiviere den WAP Push Message Routing Service (Um die Telemetrie und Datenerfassung zu unterbinden)"
$checkBox43.Text = "Deaktiviere den Heruntergeladene Karten Manager (Wenn die Karten App nicht verwendet wird)"
$CheckBox44.Text = "Deaktiviere den IP Helper (Wenn kein IPv6 verwendet wird)"
$checkBox45.Text = "Deaktiviere den Programm Kompatibilitäts Assistenten Service"
$CheckBox46.Text = "Deaktiviere den Druckwarteschlangendienst (wenn kein Drucker verwendet wird)"
$CheckBox47.Text = "Deaktiviere die Remote Registry (aus Sicherheitsgründen DEAKTIVIEREN)"
$CheckBox48.Text = "Deaktiviere die Zweitanmeldung"
$CheckBox49.Text = "Deaktiviere das Security Center"
$CheckBox50.Text = "Deaktiviere den TCP/IP NetBIOS Helper (Wenn keine WORKGROUP oder Active Directory benötigt wird)"
$CheckBox51.Text = "Deaktiviere die Bildschirmtastatur und das Handschriftpanel (Wenn diese Features nicht benötigt werden)"
$CheckBox52.Text = "Deaktiviere den Windows Error Melde Service"
$CheckBox53.Text = "Deaktiviere den Windows Image Acquisition (WIA) Service (Wenn kein Scanner benötigt wird)"
$checkBox54.Text = "Deaktiviere die Windows Suche (Senkt erheblich die Festplattenauslastung)"
$CheckBox55.Text = "Deaktiviere die Tracking Services"
$checkBox57.Text = "Deaktiviere die XBox Services"
$CheckBox58.Text = "Deaktiviere den AllJoyn Router Service (Wenn kein Peer-2-Peer genutzt wird)"
$CheckBox59.Text = "Deaktiviere den Bluetooth Service (Wenn keine Bluethooth Geräte genutzt werden)"
$checkBox60.Text = "Deaktiviere den Standortservice"
$CheckBox64.Text = "Deaktiviere den Windows Phone Service"
$CheckBox65.Text = "Deaktiviere die Biometric Services"
$checkBox66.Text = "Deaktiviere den Windows Mobile Hotspot Service"
$checkBox67.Text = "Deaktiviere den Windows Media Player Network Sharing Service"
$CheckBox68.Text = "Deaktiviere den Windows Update Service"
$CheckBox69.Text = "Deaktiviere den Enterprise App Management Service"
$checkBox70.Text = "Deaktiviere den Hyper-V Service"
$CheckBox71.Text = "Deaktiviere den HomeGroup Listener"
$CheckBox72.Text = "Deaktiviere den Net.Tcp Port Sharing Service"
$CheckBox73.Text = "Deaktiviere den Routing Remote Access"
$CheckBox74.Text = "Deaktiviere den Internet Connection Sharing (ICS) Service"
$CheckBox75.Text = "Deaktiviere Superfetch (Sollte bei SSDs unbedingt deaktiviert werden, schadet auch bei HHDs nicht)"

#Scheduled Tasks
$CheckBox86.Text = "Deaktiviere Smart Screen"
$CheckBox87.Text = "Deaktiviere Microsoft Compatibility Appraiser"
$CheckBox88.Text = "Deaktiviere Programm Data Updater"
$CheckBox89.Text = "Deaktiviere Startup App Task"
$CheckBox90.Text = "Deaktiviere Proxy"
$CheckBox91.Text = "Deaktiviere Consolidator"
$CheckBox92.Text = "Deaktiviere Kernel Ceip Task"
$CheckBox93.Text = "Deaktiviere USB Ceip"
$CheckBox94.Text = "Deaktiviere Microsoft Windows Disk Diagnostic Data Collector"
$CheckBox95.Text = "Deaktiviere File History (maintenance mode)"
$CheckBox96.Text = "Deaktiviere WinSAT"
$CheckBox97.Text = "Deaktiviere Gather Network Info"
$CheckBox98.Text = "Deaktiviere Sqm-Tasks"
$CheckBox99.Text = "Deaktiviere Force Syncronize Time"
$CheckBox100.Text = "Deaktiviere Time Syncronization"
$CheckBox101.Text = "Disavle Queue Reporting"
$CheckBox102.Text = "Deaktiviere Automatic App Update"

#Windows Default Apps
$CheckBox80.Text = "Entferne 3D-Viewer"
$CheckBox103.Text = "Entferne Bing"
$CheckBox104.Text = "Entferne Zune (Groove Music)"
$CheckBox105.Text = "Entferne Photo Viewer"
$CheckBox106.Text = "Entferne Windows Community (Update 1903)"
$CheckBox107.Text = "Entferne Solitare"
$CheckBox108.Text = "Entferne Phone"
$CheckBox109.Text = "Entferne Soundrecorder"
$CheckBox110.Text = "Entferne Camera App"
$CheckBox111.Text = "Entferne Microsoft People"
$CheckBox112.Text = "Entferne Office Live"
$CheckBox113.Text = "Entferne XBox"
$CheckBox79.Text = "Deaktiviere/Entferne OneDrive"

#Misc
$CheckBox81.Text = "Deaktiviere Widnows Error Recovery beim Hochfahren"
$CheckBox82.Text = "Internet Explorer 11 Tweaks"
$CheckBox83.Text = "Libary Tweaks"
$CheckBox84.Text = "Windows Update Tweaks"
$CheckBox85.Text = "Windows Defender Tweaks"
$CheckBox56.Text = "Blockiere Telemetry Server"
$CheckBox78.Text = "Blockiere mehr Microsoft Server"
$CheckBox114.Text = "Mouse Beschleunigungs Fix"

#Tools
$Button5.Text = "Tools herunterladen"
$Button6.Text = "Ordner Öffnen"

#Side Menu
$Label4.Text = "Vorlagen"
$CheckBox62.Text = "Registry Sichern"
$CheckBox61.Text = "Wiederherstellungspunkt erstellen"
$Button17.Text = "Schließen"
$Button16.Text = "Make FPS Rain!"

   
#Tabs
$TabPage3.Text = "Home"
$TabPage1.Text = "Registry Tweaks"
$TabPage2.Text = "Lösche Dienste"
$TabPage5.Text = "Geplante Aufgaben"
$TabPage6.Text = "Windows Standart Programme"
$TabPage8.Text = "Misc."
$TabPage4.Text = "Werkzeuge"