    #Form
    $Label3.Text = "created by MinersWin"

    #Registry Tweaks
    $CheckBox1.Text = "Show Computer Shortcut on Desktop"
    $CheckBox2.Text = "Show Network Shortcut on Desktop"
    $CheckBox3.Text = "Classic vertical Icon spacing"
    $checkBox4.Text = "Lock the Taskbar"
    $CheckBox5.Text = "Always show all icons on the Taskbar"
    $checkBox6.Text = "Delay taskbar thumbnail pop-ups to 10 seconds"
    $CheckBox7.Text = "Enable Classic control panel view"
    $CheckBox8.Text = "Turn OFF Sticky Keys when SHIFT is prssed 5 Times"
    $CheckBox9.Text = "Turn OFF Filter Keys when SHIFT is pressed for 8 seconds"
    $CheckBox10.Text = "Disable Hibernation"
    $CheckBox11.Text = "Underline keyboard shortcuts and access keys"
    $CheckBox12.Text = "Show known file extensions in Explorer"
    $checkBox13.Text = "Hide indication for compressed NTFS Files"
    $CheckBox14.Text = "Show Hidden files in Explorer"
    $CheckBox15.Text = "Show super Hidden System files in Explorer"
    $CheckBox17.Text = "Replace Utilman with CMD"
    $CheckBox18.Text = "Add the option 'Processor performance core parking min cores'"
    $CheckBox19.Text = "Disable CPU core Parking"
    $CheckBox20.Text = "Remove Logon screen wallpaper/background. Will use solid color instead (Accent color)"
    $CheckBox21.Text = "Disable lockscreen"
    $CheckBox22.Text = "Remove versioning tab from properties"
    $CheckBox23.Text = "Disable jump lists"
    $CheckBox24.Text = "Disable Windows Error Reporting"
    $CheckBox25.Text = "Disable Cortana (Speech, Search Assistant, which also sends information to Microsoft)"
    $CheckBox26.Text = "Hide search box from taskbar. You can still search by pressing the win key and start typing what youre looking for"
    $CheckBox27.Text = "Disable MRU lists (jump lists) of XAML apps in Start Menu"
    $CheckBox29.Text = "Disable Disk Quota tab, which appears as a tab when right-clicking on drive letter - Properties"
    $CheckBox30.Text = "Disable creation of an Advertising ID"
    $CheckBox31.Text = "Remove 'Pin to Start'"
    $CheckBox32.Text = "Disable Cortana, Bing, Search and Searchbar"
    $CheckBox33.Text = "Turn off the Error Dialog"
    $CheckBox34.Text = "Disable Administrative shares"
    $CheckBox35.Text = "Add 'Reboot to Recovery' to right-click menu of 'This PC'"
    $CheckBox36.Text = "Change Clock and Date formats of current User to: 24H, metric"
    $CheckBox37.Text = "Enable Developer Mode"
    $Checkbox38.Text = "remove telemetry and data collection"
    $CheckBox28.Text = "Set Windows Explorer to start on 'This PC' instead of 'Quick Access'"
    $CheckBox16.Text = "Prevent both windows and Office from creating LNK files in the Recents folder"
    $CheckBox76.Text = "Show User Profile on Desktop"
    $CheckBox77.Text = "Show Control Panel on Desktop"

    #Removing Services
    $CheckBox39.Text = "Disable Connected User Experiences and Telemetry (To turn off Telemetry and data collection)"
    $CheckBox40.Text = "Disable Diagnostic Policy Service"
    $checkBox41.Text = "Disable Distributed Link Tracking Client (If your computer is not connected to any network)"
    $CheckBox42.Text = "Disable WAP Pust Message Routing Service (To turn off Telemetry and Data Collection)"
    $checkBox43.Text = "Disable Downloaded Maps Manager (If you dont use Maps app)"
    $CheckBox44.Text = "Disable IP Helper (If you dont use IPv6 Connection)"
    $checkBox45.Text = "Disable Program Compatibility Assistant Service"
    $CheckBox46.Text = "Disable Printer Spooler (If you dont have a printer)"
    $CheckBox47.Text = "Disable Remote Registry (You can set it to DISABLED for Security purposes"
    $CheckBox48.Text = "Disable Secondary Logon"
    $CheckBox49.Text = "Disable Security center"
    $CheckBox50.Text = "Disable TCP/IP NetIOS Helper (If you are not in a workgroup network)"
    $CheckBox51.Text = "Disable Touch Keyboard and Handwriting Panel Service (If you dont want to use touch keyboard and handwriting features)"
    $CheckBox52.Text = "Disable Windows error Reporting Service"
    $CheckBox53.Text = "Disable Windows Image Acquisition (WIA) (If you dont have a scanner)"
    $checkBox54.Text = "Disable Windows Search"
    $CheckBox55.Text = "Disable tracking services"
    $checkBox57.Text = "Disable Xbox Services"
    $CheckBox58.Text = "Disable AllJoyn Router Services (If ou dont use Peer2Peer)"
    $CheckBox59.Text = "Disable Bluetooth Services"
    $checkBox60.Text = "Disable Geolocation Service"
    $CheckBox64.Text = "Disable Phone Service"
    $CheckBox65.Text = "Disable Windows Biometric Service"
    $checkBox66.Text = "Disable Windows Mobile Hotspot Service"
    $checkBox67.Text = "Disable Windows Media Player Network Sharing"
    $CheckBox68.Text = "Disable Windows Update Service"
    $CheckBox69.Text = "Disable Enterprise App Management Service"
    $checkBox70.Text = "Disable Hyper-V Services"
    $CheckBox71.Text = "Disable HomeGroup Listener"
    $CheckBox72.Text = "Disable Net.Tcp Port Sharing Service"
    $CheckBox73.Text = "Disable Routing and Remote Access"
    $CheckBox74.Text = "Disable Internet Connection Sharing (ICS)"
    $CheckBox75.Text = "Disable Superfetch (A must for SSD drives, but good in general)"

    #Scheduled Tasks
    $ComboBox86.Text = "Disable Smart Screen Specific"
    $ComboBox87.Text = "Disable Microsoft Compatibility Appraiser"
    $ComboBox88.Text = "Disable Programm Data Updater"
    $ComboBox89.Text = "Disable Startup App Task"
    $ComboBox90.Text = "Disable Proxy"
    $ComboBox91.Text = "Disable Consolidator"
    $ComboBox92.Text = "Disable Kernel Ceip Task"
    $ComboBox93.Text = "Disable USB Ceip"
    $ComboBox94.Text = "Disable Microsoft Windows Disk Diagnostic Data Collector"
    $ComboBox95.Text = "Disable File History (maintenance mode)"
    $ComboBox96.Text = "Disable WinSAT"
    $ComboBox97.Text = "Disable Gather Network Info"
    $ComboBox98.Text = "Disable Sqm-Tasks"
    $ComboBox99.Text = "Disable Force Syncronize Time"
    $ComboBox100.Text = "Disable Time Syncronization"
    $ComboBox101.Text = "Disavle Queue Reporting"
    $ComboBox102.Text = "Disable Automatic App Update"

    #Windows Default Apps
    $ComboBox80.Text = "Remove 3D-Viewer"
    $ComboBox103.Text = "Remove Bing"
    $ComboBox104.Text = "Remove Zune (Groove Music)"
    $ComboBox105.Text = "Remove Photo Viewer"
    $ComboBox106.Text = "Remove Windows Community (Update 1903)"
    $ComboBox107.Text = "Remove Solitare"
    $ComboBox108.Text = "Remove Phone"
    $ComboBox109.Text = "Remove Soundrecorder"
    $ComboBox110.Text = "Remove Camera App"
    $ComboBox111.Text = "Remoce Microsoft People"
    $ComboBox112.Text = "Remove Office Live"
    $ComboBox113.Text = "Remoce XBox"
    $ComboBox79.Text = "Disable/Remove OneDrive"

    #Misc
    $ComboBox81.Text = "Disable Widnows Error Recovery on Startup"
    $ComboBox82.Text = "Internet Explorer 11 Tweaks"
    $ComboBox83.Text = "Libary Tweaks"
    $ComboBox84.Text = "Windows Update Tweaks"
    $ComboBox85.Text = "Windows Defender Tweaks"
    $ComboBox56.Text = "Blocking Telemetry Servers"
    $ComboBox78.Text = "Blocking more Microsoft Servers"
    $ComboBox114.Text = "Mouse Acceleration Fix"

    #Tools
    $Button5.Text = "Download Tools"
    $Button6.Text = "Open Folder"

    #Side Menu
    $Label4.Text = "Templates"
    $CheckBox62.Text = "Backup Registry"
    $CheckBox61.Text = "Create System Recovery Point"
    $Button17.Text = "Close"
    $Button16.Text = "Make FPS Rain!"

    #Settings
    $Label19.Text = "Application"
    $Label20.Text = "Name"
    $Label21.Text = "Startup Message"
    $Label22.Text = "Icon"
    $Label23.Text = "Logo"
    $Label24.Text = "Language"
    $Label31.Text = "Standart Template"

    $Label25.Text = "Directory"
    $Label26.Text = "Logs"
    $Label27.Text = "Tools"
    $Label28.Text = "Backup"
    $Label29.Text = "Updates"
    $Label30.Text = "Scripts"

    $Button34.Text = "Confirm"
